# Generated by Django 5.1.1 on 2024-10-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_post',
            name='due_date',
        ),
    ]
